version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://sdsarode2812:.JCpRZt6jmmY_k5@cluster0.5drse.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

