version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend-fastify
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"


